// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchattenclownBot.Persistence.DataAccess.MSSQL;

#nullable disable

namespace SchattenclownBot.Migrations.SympathySystemDBAMigrations
{
    [DbContext(typeof(SympathySystemDBA))]
    [Migration("20231120111848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchattenclownBot.Models.SympathySystem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GuildID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetMemberID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VotingMemberID")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("ID");

                    b.ToTable("SympathySystems");
                });
#pragma warning restore 612, 618
        }
    }
}
