// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchattenclownBot.Persistence.DataAccess.MSSQL;

#nullable disable

namespace SchattenclownBot.Migrations
{
    [DbContext(typeof(TwitchNotifierDBA))]
    [Migration("20231119141806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchattenclownBot.Integrations.Discord.Services.TwitchNotifier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("DiscordGuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("DiscordMemberId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("DiscordRoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("TwitchChannelUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TwitchUserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("ID");

                    b.ToTable("TwitchNotifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
