// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchattenclownBot.DataAccess.MSSQL;

#nullable disable

namespace SchattenclownBot.Migrations
{
    [DbContext(typeof(UserLevelSystemDBA))]
    [Migration("20231112103552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchattenclownBot.Models.UserLevelSystem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DiscordGuildID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("DiscordMemberID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("OnlineTicks")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OnlineTime")
                        .HasColumnType("time");

                    b.Property<double>("VoteRatingAverage")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("UserLevelSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
