// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchattenclownBot.Persistence.DataAccess.MSSQL;

#nullable disable

namespace SchattenclownBot.Migrations.TimerDBAMigrations
{
    [DbContext(typeof(TimerDBA))]
    [Migration("20231120130312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchattenclownBot.Models.Timer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("ChannelID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("MemberID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Timers");
                });
#pragma warning restore 612, 618
        }
    }
}
